apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api
        image: us-central1-docker.pkg.dev/project-0a6400db-0297-4323-a8f/week6-repo/iris-api:v1
        ports:
        - containerPort: 8000

