name: Week 7 CI/CD + Stress Test

on:
  push:
    branches:
      - main
      - week_7
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  CLUSTER_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE_NAME: demo-log
  REPOSITORY: week6-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/938959281806/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@project-0a6400db-0297-4323-a8f.iam.gserviceaccount.com

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials \
          $CLUSTER_NAME \
          --zone $CLUSTER_ZONE

      - name: Build Docker Image
        run: |
          docker build \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push \
          us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/demo-log-ml-service \
          fastapi-container=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/demo-log-ml-service

      - name: Install wrk
        run: |
          sudo apt-get update
          sudo apt-get install -y wrk

      - name: Wait for LoadBalancer
        run: |
          sleep 20

      - name: Stress Test
        run: |
          wrk -t4 -c1000 -d30s --latency \
          -s post.lua \
          http://${{ secrets.LOAD_BALANCER_IP }}/predict

      - name: Show HPA
        run: |
          kubectl get hpa

      - name: Show Pods
        run: |
          kubectl get pods -o wide
